# Properties
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.19.3
fabric_version=0.107.0+1.21.1

# Mod Properties
mod_version=1.0.0
maven_group=com.acrous
archives_base_name=acrous-mod

# Fabric Properties
# 检查这些版本是否正确
# https://fabricmc.net/develop/

# 运行时选项
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true

# Java 工具链自动下载
org.gradle.java.installations.auto-download=true

# ==========在这里填入你的JDK21路径，斜杠用 / 不要用反斜杠\ ==========
# org.gradle.java.home=C:\Users\Lenovo\Downloads\jdk21\jdk-21.0.12